DROP TABLE MEMBER;
DROP TABLE STUDY_GROUP;
DROP SEQUENCE SEQ_STUDY_GROUP_NO;
DROP TABLE STUDY_GROUP_COMMENT;
DROP SEQUENCE SEQ_COMMENT_NO;

CREATE TABLE MEMBER (
    ID   VARCHAR2(50) PRIMARY KEY,
    PASSWORD  VARCHAR2(100) NOT NULL,
    NAME      VARCHAR2(50) NOT NULL,
    EMAIL     VARCHAR2(100) NOT NULL,
    REG_DATE  DATE DEFAULT SYSDATE
);

CREATE TABLE STUDY_GROUP (
    NO NUMBER(5) PRIMARY KEY,
    ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    CATEGORY VARCHAR2(50) NOT NULL,
    REGION VARCHAR2(50) NOT NULL,
    CONTENT CLOB,
    MAX_MEMBERS NUMBER NOT NULL,
    END_DATE DATE,
    REG_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_STUDY_GROUP_MEMBER
    FOREIGN KEY (ID)
    REFERENCES MEMBER(ID)
);

CREATE SEQUENCE SEQ_STUDY_GROUP_NO
 START WITH 1
 INCREMENT BY 1;
 
CREATE TABLE STUDY_GROUP_COMMENT (
    COMMENT_NO NUMBER PRIMARY KEY,
    STUDY_GROUP_NO NUMBER NOT NULL,
    ID VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_COMMENT_GROUP
    FOREIGN KEY (STUDY_GROUP_NO)
    REFERENCES STUDY_GROUP(NO),
    CONSTRAINT FK_COMMENT_MEMBER
    FOREIGN KEY (ID)
    REFERENCES MEMBER(ID)
);

CREATE SEQUENCE SEQ_COMMENT_NO
 START WITH 1
INCREMENT BY 1;

INSERT INTO MEMBER(ID, PASSWORD, NAME, NICKNAME, EMAIL)
VALUES('admin', 'admin1234', '관리자', 'ADMIN', 'hsg8815@naver.com');
 
INSERT INTO STUDY_GROUP(NO, ID, TITLE, CATEGORY, REGION, CONTENT, MAX_MEMBERS, END_DATE)
VALUES(SEQ_STUDY_GROUP_NO.NEXTVAL, 'HSG8815', '제목02', '면접', '성남', '면접 스터디 그룹 모집합니다', 5, '2025-05-10');
 
